### PR TITLE
#117 Fix waiting for PVC to be resized on "AzureDisk"-storage

### LINKED ISSUE #117: Fix infinity loop after PVC resize in AKS
Different cluster provider docs do not necesserily explain storage expansion in detail. In MS Azure the dogu operator will fall into an infinity loop waiting for `.status.capacity` to change which may not happen.

The correct way to wait for storage expansion is to wait for the PVC's `.status.conditions[].type=FileSystemResizePending` being true.

### PR DESCRIPTION
**Pull request by kahoona77**
resolves #117

### CODE REVIEW

File: controllers/doguVolumeManager.go [hunk 1]
```diff
@@ -264,5 +264,16 @@ func (c *checkIfPVCIsResizedStep) waitForPVCResize(ctx context.Context, doguReso
 }
 
 func isPvcStorageResized(pvc *corev1.PersistentVolumeClaim, quantity resource.Quantity) bool {
+	// first check if the filesystem resize is "pending", which means that the pod has to be (re)started to actually resize the volume
+	// see https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/#file-system-expansion
+	for _, condition := range pvc.Status.Conditions {
```
Comment (ppxl) [inline controllers/doguVolumeManager.go:269]: This is delicate stuff because we return on different conditions for different storage controllers. Currently I reflect on this longhorn issue longhorn/longhorn#2749 which states that the matching event `FileSystemResizePending` IS raised but nothing can happen until the mounting pod is up.

We should at least log both occasions to have more insight if things still go wrong but for other reasons.

Another thing. This method is quite comment-y. This is okay as long as code cannot express these circumstances. Yet I feel we can push the envelope a little bit further like with variables but first I think we need to review our procedure of scaling up and down the deployment.

File: controllers/doguVolumeManager_test.go [hunk 2]
```diff
@@ -345,6 +413,40 @@ func Test_checkIfPVCIsResizedStep_execute(t *testing.T) {
 		require.Error(t, err)
 		assert.ErrorContains(t, err, "pvc resizing is in progress")
 	})
+
+	t.Run("should return requeue error if size is not changed and there is no condition FileSystemResizePending", func(t *testing.T) {
+		// given
+		dogu := readDoguCr(t, ldapCrBytes)
+		oldSize := dogu.Spec.Resources.DataVolumeSize
+		defer func() {
```
Comment (ppxl) [inline controllers/doguVolumeManager_test.go:421]: Why is there a `defer` for local variables?

**Review by ppxl — COMMENTED** [review]
Thank you for your work. Under the light of the linked longhorn issue (see below) I am unsure if the gone direction is the right one. For me it sounds as if longhorn already DOES emit the right behaviour if we did our part the right way. And maybe our deployment scaling didn't just cut it.

File: controllers/doguVolumeManager.go (hunk 1 above)
Comment (ppxl) [reply controllers/doguVolumeManager.go:280]: Indeed Longhorn has a different status setting than the controller for Azure disks. We keep using this methology because it adds fail-safety for other controllers at best. At minimum this is a longhorn workaround.

**Comment by ppxl** [comment]
LGTM
